### ISSUE TITLE
Please enter a number warning

### ISSUE THREAD

**Issue by a0g83agbc84** [torinmb/Batch-Image-Resizer-iOS#1]
I cannot resize images. After I select the image/folder, it asks me to enter a number (not sure what number should be). I introduce a number and a warning message appears: "Please enter a number".

**Comment by torinmb** [comment]
In most cases there is a base width and height that you would like the smallest resolution image to appear at. For example if you want a 40X40 button, you would start off with a high resolution image of the button, select the image and then enter 40, which will create 3 images at the correct resolution for iOS. The only case it would say "Please enter a number" is if you did not enter a base resolution, or did not type a number.
